# core/step_registry.py
# FROZEN — do not modify without full team review and a change log entry in spec.md
#
# To add a new class to the registry, submit the addition to Ali (P1)
# with the file path. Do not edit this file directly.

from steps.extractors.nlp_extractor       import NLPExtractor
from steps.extractors.file_extractor      import FileExtractor
from steps.extractors.db_extractor        import DBExtractor
from steps.processors.llm_generator      import LLMGenerator
from steps.processors.template_renderer  import TemplateRenderer
from steps.processors.db_fetcher         import DBFetcher
from steps.dispatchers.email_dispatcher  import EmailDispatcher
from steps.dispatchers.file_dispatcher   import FileDispatcher
from steps.dispatchers.calendar_dispatcher import CalendarDispatcher
from steps.custom.anomaly_checker        import AnomalyChecker
from steps.custom.slot_ranker            import SlotRanker
from steps.custom.queue_injector         import QueueInjector
from steps.custom.pptx_writer            import PPTXWriter

STEP_REGISTRY = {
    "extractor": {
        "NLPExtractor":  NLPExtractor,
        "FileExtractor": FileExtractor,
        "DBExtractor":   DBExtractor,
    },
    "processor": {
        "LLMGenerator":     LLMGenerator,
        "TemplateRenderer": TemplateRenderer,
        "DBFetcher":        DBFetcher,
    },
    "dispatcher": {
        "EmailDispatcher":    EmailDispatcher,
        "FileDispatcher":     FileDispatcher,
        "CalendarDispatcher": CalendarDispatcher,
    },
    "custom": {
        "AnomalyChecker": AnomalyChecker,
        "SlotRanker":     SlotRanker,
        "QueueInjector":  QueueInjector,
        "PPTXWriter":     PPTXWriter,
    },
    "agent_call": {
        "DocumentSummarizer": "configs/02_document_summarizer.json",
        "EscalationRouter":   "configs/01_escalation_router.json",
        "LeaveChecker":       "configs/04_leave_checker.json",
        "ExpenseTracker":     "configs/08_expense_tracker.json",
    },
}